aplusarchitects/app/blog/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^(?P<slug>[a-z0-9-_]+?)-(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    re_path(r'^category/(?P<slug>[a-z0-9-_]+?)-(?P<pk>[0-9]+)/$', views.category, name='category'),
]

aplusarchitects/app/dashboard/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Manage Category
    path('category/', views.category_list, name='category-list'),
    path('category/add/', views.category_add, name='category-add'),
    path('category/<int:pk>/change/', views.category_change, name='category-change'),
    path('category/<int:pk>/delete/', views.category_delete, name='category-delete'),
    # Manage Tag
    path('tag/', views.tag_list, name='tag-list'),
    path('tag/add/', views.tag_add, name='tag-add'),
    path('tag/<int:pk>/change/', views.tag_change, name='tag-change'),
    path('tag/<int:pk>/delete/', views.tag_delete, name='tag-delete'),
    # Manage Post
    path('post/', views.post_list, name='post-list'),
    path('post/add/', views.post_add, name='post-add'),
    path('post/<int:pk>/change/', views.post_change, name='post-change'),
    path('post/<int:pk>/delete/', views.post_delete, name='post-delete'),
]

aplusarchitects/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include(('app.core.urls', 'core'), namespace='core')),
    path('contact/', include(('app.contact.urls', 'contact'), namespace='contact')),
    path('blog/', include(('app.blog.urls', 'blog'), namespace='blog')),
    path('portfolio/', include(('app.portfolio.urls', 'portfolio'), namespace='portfolio')),
    path('service/', include(('app.service.urls', 'service'), namespace='service')),
    path('account/', include(('app.account.urls', 'account'), namespace='account')),
    path('dashboard/', include(('app.dashboard.urls', 'dashboard'), namespace='dashboard')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplusarchitects/app/blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from django.utils.encoding import smart_str
from django.utils.translation import gettext_lazy as _
# from django.contrib.staticfiles.templatetags.staticfiles import static
from django.templatetags.static import static
from text_unidecode import unidecode
from ..translations import TranslationProxy
from ..account.models import User


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=255)

    translated = TranslationProxy()

    class Meta:
        permissions = (
            ('manage_category', _('Manage blog categories.')),
        )

    def __str__(self):
        return self.translated.name

    def get_num_post(self):
        return self.post.count()

    def get_slug(self):
        return slugify(smart_text(unidecode(self.name)))

    def get_absolute_url(self):
        return reverse(
            'blog:category', kwargs={'slug': self.get_slug(), 'pk': self.pk}
        )


class CategoryTranslation(models.Model):
    language_code = models.CharField(max_length=10, choices=settings.LANGUAGES)
    category = models.ForeignKey(
        Category, related_name='translations', on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)

    class Meta:
        unique_together = ('language_code', 'category')

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(_('Name'), max_length=50)

    translated = TranslationProxy()

    class Meta:
        permissions = (
            ('manage_tag', _('Manage blog tags.')),
        )

    def __str__(self):
        return self.translated.name

    def get_slug(self):
        return slugify(smart_text(unidecode(self.name)))

    def get_absolute_url(self):
        return reverse(
            'blog:tag', kwargs={'slug': self.get_slug(), 'pk': self.pk}
        )


class TagTranslation(models.Model):
    language_code = models.CharField(max_length=10, choices=settings.LANGUAGES)
    tag = models.ForeignKey(
        Tag, related_name='translations', on_delete=models.CASCADE
    )
    name = models.CharField(max_length=50)

    class Meta:
        unique_together = ('language_code', 'tag')

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(_('Title'), max_length=255)
    description = models.CharField(_('Description'), max_length=150)
    content = models.TextField(_('Content'))
    image = models.ImageField(upload_to='blog/%Y/%m/%d/', blank=True)
    author = models.ForeignKey(
        User, related_name='post', on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category, related_name='post', on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, related_name='post', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    translated = TranslationProxy()

    class Meta:
        permissions = (
            ('manage_post', _('Manage blog posts.')),
        )

    def __str__(self):
        return self.translated.title

    def get_slug(self):
        return slugify(smart_text(unidecode(self.title)))

    def get_absolute_url(self):
        return reverse(
            'blog:detail', kwargs={'slug': self.get_slug(), 'pk': self.pk}
        )

    def get_display_image(self):
        if self.image:
            return self.image.url
        return static('storefront/images/pages/blog/1240x800.png')


class PostTranslation(models.Model):
    language_code = models.CharField(max_length=10, choices=settings.LANGUAGES)
    post = models.ForeignKey(
        Post, related_name='translations', on_delete=models.CASCADE
    )
    title = models.CharField(_('Title'), max_length=255)
    content = models.TextField(_('Content'))

    class Meta:
        unique_together = ('language_code', 'post')

    def __str__(self):
        return self.title

aplusarchitects/app/dashboard/blog/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from ...blog.models import Category, Tag, Post


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = []


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        exclude = []


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['author']
        labels = {
            'category': _('Category'),
            'tag': _('Tag'),
            'image': _('Image'),
        }
        help_texts = {
            'image': _('Image size 1240 × 800.'),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        select2_no_search = {
            'data-plugin': 'select2',
            'data-minimum-results-for-search': 'Infinity',
            'data-placeholder': _('Select an option')
        }
        self.fields['category'].widget.attrs.update(select2_no_search)
        self.fields['tag'].widget.attrs.update({'data-plugin': 'select2'})

aplusarchitects/app/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
from .filters import PostFilter
from ..utils import get_paginator_items


def index(request):
    posts = Post.objects.all().order_by('-id')

    last_posts = posts.order_by('-created_at')[:4]
    tags = None
    categories = Category.objects.all().order_by('-id')

    post_filter = PostFilter(request.GET, queryset=posts)
    posts = get_paginator_items(
        post_filter.qs,
        5,
        request.GET.get('page')
    )

    ctx = {
        'posts': posts,
        'filter': post_filter,
        'last_posts': last_posts,
        'categories': categories,
    }
    return render(request, 'blog/index.html', ctx)


def detail(request, slug, pk):
    post = get_object_or_404(Post, pk=pk)
    related_posts = Post.objects.filter(category=post.category).exclude(
        pk=post.pk).order_by('-created_at')[:4]
    categories = Category.objects.all().order_by('-id')
    ctx = {
        'post': post,
        'related_posts': related_posts,
        'categories': categories
    }
    return render(request, 'blog/detail.html', ctx)


def category(request, slug, pk):
    category = get_object_or_404(Category, pk=pk)
    posts = Post.objects.filter(category=category).order_by('-id')
    posts = get_paginator_items(
        posts,
        5,
        request.GET.get('page')
    )
    ctx = {'category': category, 'posts': posts}
    return render(request, 'blog/category.html', ctx)

aplusarchitects/app/dashboard/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.utils.translation import gettext_lazy as _
from ...blog.models import Category, Tag, Post
from ..utils import get_paginator_items, staff_member_required
from .forms import CategoryForm, TagForm, PostForm
from .filters import PostFilter


@staff_member_required
@permission_required('blog.manage_category')
def category_list(request):
    categories = Category.objects.all().order_by('-id')
    categories = get_paginator_items(
        categories,
        settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page')
    )
    ctx = {'categories': categories}
    return render(request, 'dashboard/blog/category/list.html', ctx)


@staff_member_required
@permission_required('blog.manage_category')
def category_add(request):
    form = CategoryForm(request.POST or None)
    if form.is_valid():
        category = form.save()
        messages.success(request, _('Added successfully.'))
        return redirect('dashboard:blog:category-change', pk=category.pk)
    ctx = {'form': form}
    return render(request, 'dashboard/blog/category/form.html', ctx)


@staff_member_required
@permission_required('blog.manage_category')
def category_change(request, pk):
    category = get_object_or_404(Category, pk=pk)
    form = CategoryForm(request.POST or None, instance=category)
    if form.is_valid():
        category = form.save()
        messages.success(request, _('Updated successfully.'))
        return redirect('dashboard:blog:category-change', pk=category.pk)
    ctx = {'category': category, 'form': form}
    return render(request, 'dashboard/blog/category/form.html', ctx)


@staff_member_required
@permission_required('blog.manage_category')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(request, _('Removed successfully.'))
        return redirect('dashboard:blog:category-list')
    ctx = {'category': category}
    return render(request, 'dashboard/blog/category/modal/confirm_delete.html', ctx)


@staff_member_required
@permission_required('blog.manage_tag')
def tag_list(request):
    tags = Tag.objects.all().order_by('-id')
    tags = get_paginator_items(
        tags,
        settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page')
    )
    ctx = {'tags': tags}
    return render(request, 'dashboard/blog/tag/list.html', ctx)


@staff_member_required
@permission_required('blog.manage_tag')
def tag_add(request):
    form = TagForm(request.POST or None)
    if form.is_valid():
        tag = form.save()
        messages.success(request, _('Added successfully.'))
        return redirect('dashboard:blog:tag-change', pk=tag.pk)
    ctx = {'form': form}
    return render(request, 'dashboard/blog/tag/form.html', ctx)


@staff_member_required
@permission_required('blog.manage_tag')
def tag_change(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    form = TagForm(request.POST or None, instance=tag)
    if form.is_valid():
        tag = form.save()
        messages.success(request, _('Updated successfully.'))
        return redirect('dashboard:blog:tag-change', pk=tag.pk)
    ctx = {'tag': tag, 'form': form}
    return render(request, 'dashboard/blog/tag/form.html', ctx)


@staff_member_required
@permission_required('blog.manage_tag')
def tag_delete(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    if request.method == 'POST':
        tag.delete()
        messages.success(request, _('Removed successfully.'))
        return redirect('dashboard:blog:tag-list')
    ctx = {'tag': tag}
    return render(request, 'dashboard/blog/tag/modal/confirm_delete.html', ctx)


@staff_member_required
@permission_required('blog.manage_post')
def post_list(request):
    posts = Post.objects.all().order_by('-created_at')
    post_filter = PostFilter(request.GET, queryset=posts)
    posts = get_paginator_items(
        post_filter.qs,
        settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page')
    )
    ctx = {'posts': posts, 'filter': post_filter}
    return render(request, 'dashboard/blog/post/list.html', ctx)


@staff_member_required
@permission_required('blog.manage_post')
def post_add(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        for tag in form.cleaned_data['tag']:
            post.tag.add(tag)

        messages.success(request, _('Added successfully.'))
        return redirect('dashboard:blog:post-change', pk=post.pk)
    ctx = {'form': form}
    return render(request, 'dashboard/blog/post/form.html', ctx)


@staff_member_required
@permission_required('blog.manage_post')
def post_change(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        post = form.save()
        messages.success(request, _('Updated successfully.'))
        return redirect('dashboard:blog:post-change', pk=post.pk)
    ctx = {'post': post, 'form': form}
    return render(request, 'dashboard/blog/post/form.html', ctx)


@staff_member_required
@permission_required('blog.manage_post')
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post.delete()
        messages.success(request, _('Removed successfully.'))
        return redirect('dashboard:blog:post-list')
    ctx = {'post': post}
    return render(request, 'dashboard/blog/post/modal/confirm_delete.html', ctx)

aplusarchitects/templates/dashboard/blog/category/form.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}

{% block title %}
    {% if category %}
        {{ category }} - {{ block.super }}
    {% else %}
        {% trans 'Add category' context 'Page title' %} - {{ block.super }}
    {% endif %}
{% endblock %}

{% block body_class %}{% endblock %}
{% block blog_class %}active open{% endblock %}
{% block blog_category_class %}active{% endblock %}

{% block page %}
<!-- Page -->
<div class="page">
    <div class="page-header">
        <h1 class="page-title">
            {% if category %}
                {{ category }}
            {% else %}
                {% trans 'Add category' context 'Page title' %}
            {% endif %}
        </h1>
        <div class="page-header-actions">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'dashboard:index' %}">{% trans 'Dashboard' context 'Breadcrumb item' %}</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="javascript:void(0)">{% trans 'Blog' context 'Breadcrumb item' %}</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'dashboard:blog:category-list' %}">{% trans 'Categories' context 'Breadcrumb item' %}</a>
                </li>
                <li class="breadcrumb-item active">
                    {% if category %}
                        {{ category }}
                    {% else %}
                        {% trans 'Add category' context 'Breadcrumb item' %}
                    {% endif %}
                </li>
            </ol>
        </div>
    </div>
    <div class="page-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel">
                    <div class="panel-body">
                        <form action="" method="POST" novalidate>{% csrf_token %}
                            {% bootstrap_field form.name %}
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary float-right">
                                    {% if category %}
                                        {% trans 'Update' context 'Button text' %}
                                    {% else %}
                                        {% trans 'Add' context 'Button text' %}
                                    {% endif %}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Page -->
{% endblock %}

{% block plugin_css %}{% endblock %}
{% block page_css %}{% endblock %}
{% block plugin_js %}{% endblock %}
{% block page_js %}{% endblock %}

aplusarchitects/templates/dashboard/blog/category/list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load i18n %}
{% load paginate %}

{% block title %}
    {% trans 'Categories' context 'Page title' %} - {{ block.super }}
{% endblock %}

{% block body_class %}{% endblock %}
{% block blog_class %}active open{% endblock %}
{% block blog_category_class %}active{% endblock %}

{% block page %}
<!-- Page -->
<div class="page">
    <div class="page-header">
        <h1 class="page-title">{% trans 'Categories' context 'Page title' %}</h1>
        <div class="page-header-actions">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'dashboard:index' %}">{% trans 'Dashboard' context 'Breadcrumb item' %}</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="javascript:void(0)">{% trans 'Blog' context 'Breadcrumb item' %}</a>
                </li>
                <li class="breadcrumb-item active">{% trans 'Categories' context 'Breadcrumb item' %}</li>
            </ol>
        </div>
    </div>
    <div class="page-content">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel">
                    <div class="panel-heading"></div>
                    <div class="panel-body">
                        <form action="" method="get" class="form-inline" style="margin: 20px 0px; float: right;">
                            <div class="form-group">
                                <a href="{% url 'dashboard:blog:category-add' %}" class="btn btn-primary">
                                    {% trans 'Add category' context 'Button text' %}
                                </a>
                            </div>
                        </form>
                        <div class="table-responsive">
                            <table class="table table-bordered table-vertical-align">
                                <thead class="bg-blue-grey-100">
                                    <tr>
                                        <th style="width: 100px;">{% trans 'ID' context 'Table header text' %}</th>
                                        <th>{% trans 'Name' context 'Table header text' %}</th>
                                        <th style="width: 100px;">{% trans 'Action' context 'Table header text' %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if categories %}
                                {% for cat in categories %}
                                <tr>
                                    <td>{{ cat.id }}</td>
                                    <td>{{ cat }}</td>
                                    <td>
                                        <a href="{% url 'dashboard:blog:category-change' pk=cat.pk %}" class="btn btn-sm btn-icon btn-info">
                                            <i class="icon wb-edit" aria-hidden="true"></i>
                                        </a>
                                        <a href="#base-modal" data-href="{% url 'dashboard:blog:category-delete' pk=cat.pk %}" class="btn btn-sm btn-icon btn-danger modal-trigger-custom">
                                            <i class="icon wb-trash" aria-hidden="true"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                                {% else %}
                                <tr><td colspan="3" class="text-center">{% trans 'No data.' context 'Table no data' %}</td></tr>
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                        <div style="float:right;">
                            {% paginate categories %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Page -->
{% endblock %}

{% block plugin_css %}{% endblock %}
{% block page_css %}{% endblock %}
{% block plugin_js %}{% endblock %}
{% block page_js %}{% endblock %}